runtime: nodejs16

service: wastease-service-account

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: fluent-stratum-345612:us-central1:waste-app
  # Enable Google Cloud Endpoints API management.
  use_endpoints_api_management: true
  # Specify the Open API specification.
  endpoints_swagger_spec_file: openapi.yaml

env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/fluent-stratum-345612:us-central1:waste-app
  DB_USER: waste-app-user
  DB_NAME: waste
  DB_PASS: wasteapp101
  DB_INSTANCE: fluent-stratum-345612:us-central1:waste-app
  # TESTVAR: "hehehe"
  # TWILIO_SID: "XYZ1234PBJ"
  # TWILIO_AUTH_TOKEN: "XYZ1234PBJ"
  # GOOGLE_CLIENT_ID: "776569245382-gi0gi9vmonbak73nhsocnibq801f95iu.apps.googleusercontent.com"
  # GOOGLE_CLIENT_SECRET: "xyz1234-PBJ"git remote set-url origin link